name: CI (Nix)

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development


jobs:
  do-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v5
      - name: Install nixpkgs
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Pre-process dev shell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
      - name: Install dependencies
        run: nix develop . --command pnpm install
      - name: Run CI
        run: nix develop . --command pnpm -r run check