name: Continous Integration

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

permissions:
  contents: read
  packages: write

jobs:
  Run-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v5
      - name: Install nixpkgs
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Pre-process dev shell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
      - name: Install dependencies
        run: nix develop . --command pnpm install --frozen-lockfile
      - name: Build applications
        run: nix develop . --command pnpm -r --filter=@dndevops/app-* run build
      - name: Run checks on all packages
        run: nix develop . --command pnpm -r run check
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate tag
        id: docker-tag
        run: |
          echo "VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_NAME}" == "development" ]]; then
            echo "TAG=dev" >> $GITHUB_OUTPUT
            echo "SUFFIX=-dev" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          fi
      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./images/packed/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/dndevops:${{ steps.docker-tag.outputs.TAG }}
            ghcr.io/${{ env.OWNER_LC }}/dndevops:${{ steps.docker-tag.outputs.VERSION }}${{ steps.docker-tag.outputs.SUFFIX }}
      - name: Create image
        run: docker build --file images/packed/Dockerfile . --tag dndevops:latest
      